liquor_sales:
  target: jaffle_sql
  outputs:
    jaffle_sql:
      type: bigquery
      method: oauth
      project: my-project-ntu-478012
      dataset: liquor_demo
      threads: 4
      location: US
      priority: interactive
      retries: 2
  config:
    send_anonymous_usage_stats: False
